version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5433/stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm


  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=ewm
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root